###add user

POST https://u-nine-beta.vercel.app/todo
Content-Type: application/json

{
  "title": 3,
  "description": 23,
  "completed":false
}


###Find all todos

get https://u-nine-beta.vercel.app/todo







### find a current user

get http://localhost:3000/todo/67b2e65162b40e1a7f349a58




### Update todo

PATCH  https://u-nine-beta.vercel.app/todo/67b2e65162b40e1a7f349a58
Content-Type: application/json


{
    "title": "Playing todo",
    "description": "Need to play cricket",
    "completed": false
}


### Delete a todo

DELETE   http://localhost:3000/todo/67b2e2f100ed18ec6a8cbd80
Content-Type: application/json


{
    "title": "PLaying game",
    "description": "Need to play cricket",
    "completed": false
}