###Register a user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"tanvir@gmail.com",
  "password":"b@b.com"
}
###sign out

GEt http://localhost:3000/auth/signout



###login a user

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"tanvir@gmail.com",
  "password":"b@b.com"
}

###add user

POST http://localhost:3000/todo
Content-Type: application/json

{
  "title": "e45",
  "description": "fd4",
  "completed":false
}



###Find all todos


GET  http://localhost:3000/todo


### find a current user

get  http://localhost:3000/todo/67b35a5b1679d2cbffd8d695




### Update todo

PATCH  http://localhost:3000/todo/67be2fc7b45e038c7ee66cca
Content-Type: application/json


{
    "title": "Playing todos",
    "description": "Need to play cricket",
    "completed": false
}


### Delete a todo

DELETE   https://todo-nest-2smq.vercel.app/todo/67b2ff16ef09c11bebb36a0b
Content-Type: application/json


{
    "title": "PLaying game",
    "description": "Need to play cricket",
    "completed": false
}