###Register a user

POST http://localhost:3000/auth/signup
Content-Type: application/json

# {
#   "email":"tanvir@gmail.com",
#   "password":"b@b.com"
# }
{
    "email":"tanvir@t.com",
    "password":"password"
}
###sign out

GEt http://localhost:3000/auth/signout



###login a user

POST http://localhost:3000/auth/login
Content-Type: application/json

# {
#     "email":"tanvir@t.com",
#     "password":"password"
# }
{
  "email":"tanvir@gmail.com",
  "password":"b@b.com"
   }
###add user

POST http://localhost:3000/todo
Content-Type: application/json

{
  "title": "e45w",
  "description": "fdd4",
  "completed":true
}



###Find all todos


GET  http://localhost:3000/todo


### find a current user

get  http://localhost:3000/todo/67bf0689c4604e1456afab8c




### Update todo

PATCH  http://localhost:3000/todo/67bf0689c4604e1456afab8c
Content-Type: application/json


{
    "title": "Playing todoss",
    "description": "Need to play cricket",
    "completed": false
}


### Delete a todo

DELETE   http://localhost:3000/todo/67bf0689c4604e1456afab8c
Content-Type: application/json


{
    "title": "PLaying game",
    "description": "Need to play cricket",
    "completed": false
}